### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by wolkyura** [framer/motion#1596]
**2. Describe the bug**

The animation breaks when the body is not used as a scroll container, e.g.:

```css
body {
  height: 100%;
  overflow: hidden;
}

.scrollContainer {  (#inside body)
  height: 100%;
  overflow-y: scroll;
}
```

The issue occurs in all versions after `>4.1.17`.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/silent-http-ry31jc?file=/src/App.js

**4. Steps to reproduce**

1. Go to CodeSandbox link  
2. Try to filter cards by clicking checkboxes 
3. Scroll up/down a bit
4. Filter cards by clicking checkboxes one more time
5. See that animation breaks for some cards

**5. Expected behavior**

The animation should work properly even if body is not a scroll container.

**6. Video or screenshots**

https://user-images.githubusercontent.com/54850073/175474505-8d0073bf-86c6-4845-bb0e-db25a29298cc.mov

https://user-images.githubusercontent.com/54850073/175476588-3799aa2b-1f2d-4350-abc4-dcdf6425d819.mov

<img width="400" alt="Screen Shot 2022-06-24 at 8 22 34 AM" src="https://user-images.githubusercontent.com/54850073/175475198-b50a22be-c61f-4775-a2eb-8aaf96bf6c94.png">

**7. Environment details**

All browsers, `framer-motion > v4.1.17`
