### ISSUE TITLE
[BUG] Animation with css variable fails

### ISSUE THREAD

**Issue by 233mawile** [framer/motion#1652]
**2. Describe the bug**

when animating with css variable:
1. There can be no spaces between the variable name and the value, and the value cannot be followed by a semicolon.
2. `rgb(27 233 88 / 1)` need spaces around `/`. ✅`rgb(27 233 88 / 1)` ❌`rgb(27 233 88/1)`

```jsx
function App() {
  return <motion.button whileTap={{ "--color": "#d44026" }}>bug</motion.button>;
}
```

```css
button {
  border-color: var(--color);
  color: var(--color);

  /* no bug */
  --color:#1be958;
  --color:rgb(27 233 88 / 1);

  /* bug: 'rgb(27 233 88/1)' is not an animatable color. Use the equivalent color code instead. */
  --color:rgb(27 233 88/1); 

  /* bug: ' #1be958' is not an animatable color. Use the equivalent color code instead. */
  --color: #1be958;

  /* bug: '#1be958  ' is not an animatable color. Use the equivalent color code instead. */
  --color:#1be958
}
```

similar issue: https://github.com/framer/motion/issues/546

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/framer-motion-css-variables-bug-1j61x3

**4. Steps to reproduce**

1. click button
3. See error: ' #1be958' is not an animatable color. Use the equivalent color code instead.

**5. Expected behavior**

Color transitions correctly

**6. Video or screenshots**

https://user-images.githubusercontent.com/45569305/183794900-d18e0cce-010b-487d-9c21-2b7efb2b9a13.mov

**7. Environment details**

chrome: Version 104.0.5112.79 (Official Build) (arm64)
OS: MacOS 12.4
