### ISSUE TITLE
[BUG] layoutTransition animation triggered by childs pure css animation

### ISSUE THREAD

**Issue by mrGibi** [framer/motion#295]
**Describe the bug**
If the Motion element with `layoutTransition` have a child with pure css animation, the Motion element seems to be in infinite animation. It triggers `onAnimationStart` (without triggering `onAnimationComplete` later).

**To Reproduce**
[DEMO](https://codesandbox.io/s/suspicious-wind-wwi9c)

**Expected behavior**
I expected `layoutTransition` animation not to be triggered by the Motion element children pure css animations.

**Screenshots**
[DEMO](https://codesandbox.io/s/suspicious-wind-wwi9c)

**Desktop & Mobile**
 - OS: MacOs latest, iOS latest
 - Browsers: latest Safari, Chrome and Firefox

**Additional context**
If you comment these:
```css
@keyframes spin {
  0% {
    /* transform: rotate(0deg); */
  }
  100% {
    /* transform: rotate(359deg); */
  }
}
```
its still triggers `layoutTransition` animation. But if you comment whole block:
```css
@keyframes spin {
  /* 0% {
    transform: rotate(0deg);
  }
  100% {
    transform: rotate(359deg);
  } */
}
```
`layoutTransition` isnt triggered.
