### ISSUE TITLE
[BUG] `useViewportScroll` is not updating.

### ISSUE THREAD

**Issue by saisandeepvaddi** [framer/motion#835]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

Give a clear and concise description of what the bug is.
`scrollYProgress` from `useViewportScroll` hook does not update.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

A CodeSandbox minimal reproduction will allow us to quickly follow the reproduction steps. **Without one, this bug report won't be accepted.**

**4. Steps to reproduce**

1. Go to https://codesandbox.io/s/trusting-jepsen-mikfs?file=/src/App.js
2. Open console
3. Scroll down
4. No updated `scrollYProgress` value

**5. Expected behavior**

`scrollYProgress` updates when scroll happens.

**Comment by mattgperry** [comment]
Do you have body/html set to height: 100%?

**Comment by saisandeepvaddi** [comment]
Nope.

This is the whole css

```css
body {
  padding: 0;
  margin: 0;
  display: flex;
  justify-content: center;
  align-items: center;
}

.App {
  font-family: sans-serif;
  text-align: center;
}

.grid {
  display: flex;
  flex-wrap: wrap;
  height: 800px;
}

.box {
  margin: 10;
}


```
